# Generated by Django 3.2.4 on 2021-06-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_page_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='time',
            field=models.PositiveIntegerField(),
        ),
    ]
